### ISSUE TITLE
Rsync Error

### ISSUE THREAD

**Issue by KuLiPoi** [Burnett01/rsync-deployments#12]
when i deploy a project to server , i got this error in log.  
But everything is going well, no files are missing.  It's just the red error symbol that annoys on me 

sorry for my bad English 😢 

```
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
```

**Comment by Burnett01** [comment]
Hi, very interesting issue. Do you have any logs regarding the "previous errors"? How does your workflow look like?

**Comment by KuLiPoi** [comment]
Full log here https://pastebin.com/vJCXbLKs
My workflow 
```
name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /www/wwwroot/docs/docs
        remote_host: 49.233.159.171
        remote_user: root
        remote_key: ${{ secrets.SSH_TOKEN }}
```
