### ISSUE TITLE
SSH key wrong when it isn't

### ISSUE THREAD

**Issue by zohaad** [Burnett01/rsync-deployments#14]
Hello, the program says the key is wrong when it isn't (I use the same key to connect over ssh)

```yml
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Copy binary with rsync
        uses: burnett01/rsync-deployments@5.0
        with:
          switches: -avzr -vvv
          path: target/release/microprogress
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_user: $${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
```

This is the message when ran with `-vvv`:
```

Run burnett01/rsync-deployments@5.0
/usr/bin/docker run --name bec5f4281d335037d4d46a6e33953a96d00d2_cea912 --label 3bec5f --workdir /github/workspace --rm -e INPUT_SWITCHES -e INPUT_PATH -e INPUT_REMOTE_PATH -e INPUT_REMOTE_HOST -e INPUT_REMOTE_USER -e INPUT_REMOTE_KEY -e INPUT_RSH -e INPUT_REMOTE_PORT -e INPUT_REMOTE_KEY_PASS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/microprogress/microprogress":"/github/workspace" 3bec5f:4281d335037d4d46a6e33953a96d00d2
Identity added: (stdin) ((stdin))
cmd=ssh -o StrictHostKeyChecking=no -p 22  machine=*** user= path=***
cmd[0]=ssh cmd[1]=-o cmd[2]=StrictHostKeyChecking=no cmd[3]=-p cmd[4]=22 cmd[5]=-l cmd[6]= cmd[7]=*** cmd[8]=rsync cmd[9]=--server cmd[10]=-vvvvlogDtprze.iLsfxC cmd[11]=. cmd[12]=*** 
opening connection using: ssh -o StrictHostKeyChecking=no -p 22 -l  *** rsync --server -vvvvlogDtprze.iLsfxC . ***  (13 args)
msg checking charset: UTF-8
Warning: Permanently added '***' (ECDSA) to the list of known hosts.
@***: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
[sender] _exit_cleanup(code=12, file=io.c, line=226): entered
[sender] _exit_cleanup(code=12, file=io.c, line=226): about to call exit(12)
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]```
