### ISSUE TITLE
Provide a list of files to the `src`

### ISSUE THREAD

**Issue by lfgcampos** [Burnett01/rsync-deployments#20]
I would like to do an automatic rsync but only to the files changes on my last commit.
AFAIK, rsync supports this but I am not sure if the action does or how to do it.

Using bash/git, I can get a list of changed files and would like to use them as my input `path` making sure only those files are rsync-ed.

An example would be something like this:
```yml
jobs:
  changed-files:
    name: Changed files
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"

  deploy:
    - name: Deploy to server
      id: deploy
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: '${{needs.changed-files.outputs.all}}'
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
```
