### ISSUE TITLE
Not removing delete files on server

### ISSUE THREAD

**Issue by raazon** [Burnett01/rsync-deployments#26]
If i delete/rename a file on my repository from local and push it to Github, It's not deleting/renaming on server. I attached my exact code below. Not sure i'm missing something or it's a bug.

```
name: Rsync Deployments

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: public/github
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT_STAGING }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.PRIVATE_KEY }}
```

Thanks.

**Comment by Burnett01** [comment]
Hello @raazon can you confirm rsync is behaving the right way on your server when running the action with a dry-run?

Just add --dry-run to the switches an check the actions log. Is it showing any warnings/errors?

**Comment by raazon** [comment]
@Burnett01 actually this work for me.

`switches: -avzr --exclude=".git*" --filter="dir-merge,- .gitignore" --delete-after --progress ./ ./`

**Comment by Burnett01** [comment]
Ok good to know :) Thanks for reporting

**Comment by raazon** [comment]
Full working code is below.
**Note:** It will ignore .git and all .gitignore excludes. It will replace the rest of the files each time you push(except main branch)

```
name: Staging rsync deployment by SSH/SFTP

on:
  push:
    branches-ignore: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --exclude=".git*" --filter="dir-merge,- .gitignore" --delete-after --progress ./ ./
        path: ./*
        remote_path: ${{ secrets.REMOTE_TARGET }}
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT_STAGING }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.PRIVATE_KEY }}
```
