### ISSUE TITLE
Syntax error in command?

### ISSUE THREAD

**Issue by marcelstoer** [Burnett01/rsync-deployments#36]
I am using the following simple configuration straight from the book.
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     ...
      - name: rsync deployment
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr -vvv
          path: site
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_path: ${{ secrets.DEPLOY_REMOTE_PATH }}
          remote_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
```

The action fails and I get the feeling there's a syntax somewhere in the generated command. Why else would rsync dump the help output to the console?

```
Identity added: (stdin) (***@s104.server.hostpoint.internal)
cmd=ssh -o StrictHostKeyChecking=no -p 22  machine=*** user=*** path=***
cmd[0]=ssh cmd[1]=-o cmd[2]=StrictHostKeyChecking=no cmd[3]=-p cmd[4]=22 cmd[5]=-l cmd[6]=*** cmd[7]=*** cmd[8]=rsync cmd[9]=--server cmd[10]=-vvvvlogDtprze.iLsfxCIvu cmd[11]=. cmd[12]=*** 
opening connection using: ssh -o StrictHostKeyChecking=no -p 22 -l *** *** rsync --server -vvvvlogDtprze.iLsfxCIvu . ***  (13 args)
msg checking charset: UTF-8
Warning: Permanently added '***' (ED25519) to the list of known hosts.
rsync  version 3.2.5  protocol version 31
Copyright (C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, symlinks, symtimes, hardlinks, hardlink-specials,
    hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, ACLs,
    xattrs, optional protect-args, iconv, no prealloc, stop-at, no crtimes
Optimizations:
    no SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

rsync is a file transfer program capable of efficient remote update
via a fast differencing algorithm.

Usage: rsync [OPTION]... SRC [SRC]... DEST
  or   rsync [OPTION]... SRC [SRC]... [USER@]HOST:DEST
  or   rsync [OPTION]... SRC [SRC]... [USER@]HOST::DEST
  or   rsync [OPTION]... SRC [SRC]... rsync://[USER@]HOST[:PORT]/DEST
  or   rsync [OPTION]... [USER@]HOST:SRC [DEST]
  or   rsync [OPTION]... [USER@]HOST::SRC [DEST]
  or   rsync [OPTION]... rsync://[USER@]HOST[:PORT]/SRC [DEST]
The ':' usages connect via remote shell, while '::' & 'rsync://' usages connect
to an rsync daemon, and require SRC or DEST to start with a module name.

Options
--verbose, -v            increase verbosity
...
---

Use "rsync --daemon --help" to see the daemon-mode command-line options.
Please see the rsync(1) and rsyncd.conf(5) manpages for full documentation.
See https://rsync.samba.org/ for updates, bug reports, and answers
rsync error: syntax or usage error (code 1) at main.c(1754) [client=3.2.5]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4]
[sender] _exit_cleanup(code=12, file=io.c, line=228): entered
[sender] _exit_cleanup(code=12, file=io.c, line=228): about to call exit(12)
```

If I run rsync manually on macOS using the same secrets as configured on GitHub then all is well: `rsync -avzr -e 'ssh -i ~/.ssh/my-private-key' site DEPLOY_USER@DEPLOY_HOST:DEPLOY_REMOTE_PATH`.

I am more than just a little confused.
