### ISSUE TITLE
Run with rsh option fails

### ISSUE THREAD

**Issue by devmount** [Burnett01/rsync-deployments#40]
I'm using this workflow configuration, which is working fine until I add the line with the remote shell commend:

```yaml
    - name: Push Build files to testing environment
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --exclude={'.git*','node_modules','.editorconfig','.env.*'}
        rsh: uptime # <-- this line causes the action to fail
        path: /
        remote_path: ${{ secrets.DEPLOY_PATH_DEV }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
        remote_key_pass: ${{ secrets.DEPLOY_SSH_PHRASE }}
```

I get the following error:

    ssh: Could not resolve hostname uptime: Name does not resolve

![image](https://user-images.githubusercontent.com/5441654/211007348-d9e45bb7-3e13-477b-822c-e931e50a99ae.png)

Am I doing something wrong here? Is this option not supposed to provide the possibility to run remote shell commands after deployment? I also tried with single quotes `'uptime'`, but it fails the same.

Thanks for any help on this.
