### ISSUE TITLE
Rsync missing

### ISSUE THREAD

**Issue by jakewhiteley** [Burnett01/rsync-deployments#46]
This is my current action:

```
name: DEPLOY
on:
  push:
    branches:
    - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: wp-content/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
```

And this is the action output:
```
Identity added: (stdin) ((stdin))
Warning: Permanently added '***' (ED25519) to the list of known hosts.
bash: line 1: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code [12](https://github.com/craftedbygc/cosmos/actions/runs/5222055422/jobs/9427078356#step:4:13)) at io.c(231) [sender=3.2.7]
```
