### ISSUE TITLE
I receive rsync: connection unexpectedly closed (0 bytes received so far) [sender] when using the library

### ISSUE THREAD

**Issue by MohammedShetaya** [Burnett01/rsync-deployments#48]
I provide the private key and the user of the remote ec2 machine to which want to send my files. The instance is being created successfully providing its DNS as output, but when this step runs it fails as below 

```
ssh: connect to host ec2-7-100-132-4.compute-1.amazonaws.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
```

```
    - name: 'Deploy to New Instance'
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: ./api
        remote_path: /home/${{ secrets.INSTANCE_USER }}/server
        remote_host: ${{ steps.terraform-output.outputs.stdout }}
        remote_user: ${{ secrets.INSTANCE_USER }}
        remote_key: ${{ secrets.INSTANCE_PRIVATE_KEY }}

```

The problem is that when I rerun the same workflow it runs correctly, but not the first time the instance is created. It has to fail for the first time. Any ideas what might be the problem?
