### ISSUE TITLE
Keep images folder between deploys

### ISSUE THREAD

**Issue by KosratDAhmad** [Burnett01/rsync-deployments#5]
I have `images` folder on my website which stores user's uploaded images so that I want to keep this folder between deploys to not be deleted with sync.
Is there a way to achieve that??

**Comment by Burnett01** [comment]
> I have `images` folder on my website which stores user's uploaded images so that I want to keep this folder between deploys to not be deleted with sync.
> Is there a way to achieve that??

Hello, sure thing! Simply use the --exclude switch or the --filter switch.

Here is an example (assuming your image folder is located at /var/www/images):

```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="images"
        path: src/
        remote_path: /var/www/html/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
```

If your images folder is located at a deeper level and not at remote_path, simply adjust the path to your folder in the --exclude switch:

```yml
--exclude="public/images"
```
Greetings, Steve
