### ISSUE TITLE
rsync Not Found?

### ISSUE THREAD

**Issue by jrswab** [Burnett01/rsync-deployments#55]
Getting a very unexpected error when Github actions execute:

```
Identity added: (stdin) (admin@*****.com)
Warning: Permanently added '***' (ED25519) to the list of known hosts.
ksh: rsync: not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code [12](https://github.com/jrswab/guild/actions/runs/7856477062/job/21439281458#step:4:13)) at io.c(231) [sender=3.2.7]
```

Here is what I have in my Github actions file:
```
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr
        path: guild-${{ github.ref_name }}
        remote_path: /home/builds/guild-${{ github.ref_name }}
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
```

Any insight would be greatly appreciated as to why it's telling me `rsync not found`.
