### ISSUE TITLE
burnett01/rsync-deployments@7.0.1 hangs transferring specific files

### ISSUE THREAD

**Issue by arobthearab** [Burnett01/rsync-deployments#64]
### Actual Behavior

Rsync action fails when attempting to use a path of "*.sh"

### Expected Behavior

Rsync would treat the path as it would be treated in any rsync command, in this case to synchronize all shell scripts in the root directory of the repository.

### Details

I have five rsync steps in my GitHub action, four of which work without a hitch, and are of this general form:

```
   - name: Deploy backend to ${{vars.TARGET}} ...
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: backend/
          remote_path: ${{vars.TARGET}}
          remote_host: ${{vars.HOST}}
          remote_port: ${{vars.PORT}}
          remote_user: ${{vars.USER}}
          remote_key: ${{secrets.KEY}}

```
 but the fifth attempts to copy a pattern from the base directory of the repository:

  ```
   - name: Deploy installation scripts to ${{vars.TARGET}} ...
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete
          path: "*.sh"
          remote_path: ${{vars.TARGET}}
          remote_host: ${{vars.HOST}}
          remote_port: ${{vars.PORT}}
          remote_user: ${{vars.USER}}
          remote_key: ${{secrets.KEY}}
```

The result of this operation is:

```
Connection reset by [redacted] port [redacted]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]
```

All the other successful steps use the same parameters.

Since all the other paths are relative I assume that "*.sh" would be the correct path specification to match all shell files in the root directory of the repository.

_Based on logs at the receiving end_, the first four rsyncs connect and work as expected, but the fifth to copy *.sh does not appear to connect at all.
