### ISSUE TITLE
Question: Syncing multiple folders?

### ISSUE THREAD

**Issue by debonx** [Burnett01/rsync-deployments#67]
Hey there, 

I am attempting to sync multiple folders, without duplicating configuration.
Is it possible?

for example
```
      - name: Syncing Distribution files
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: folder1, folder2, n,
```

**Comment by nils-kt** [comment]
Unfortunately, `burnett01/rsync-deployments` doesn’t support syncing multiple folders at once within the same action call. However, you can call the action multiple times in separate steps for each folder. Here’s a correct version:

```yaml
- name: Sync folder1
  uses: burnett01/rsync-deployments@7.0.1
  with:
    switches: -avzr --delete
    path: folder1/
    remote_path: /path/
    remote_host: user@remote

- name: Sync folder2
  uses: burnett01/rsync-deployments@7.0.1
  with:
    switches: -avzr --delete
    path: folder2/
    remote_path: /path/
    remote_host: user@remote

- name: Sync folderN
  uses: burnett01/rsync-deployments@7.0.1
  with:
    switches: -avzr --delete
    path: folderN/
    remote_path: /path/
    remote_host: user@remote
```

This will sync each folder separately but avoids duplication of the `rsync` configuration logic. Unfortunately, to sync multiple folders, you need to call the action once for each folder.
