### ISSUE TITLE
Can I use password?

### ISSUE THREAD

**Issue by chefranov** [Burnett01/rsync-deployments#8]
Hi! I try to use your action for deploy, but I have error "Permission denied" because I need to input password (It said hosting provider). Is it possible with you action? Or maybe I do something wrong

![Screenshot_1](https://user-images.githubusercontent.com/2775475/107156079-d54b1800-6984-11eb-9838-45ce75d4854f.png)

Code:
```
name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: /test/
        remote_host: *ip*
        remote_user: *username*
        remote_key: ${{ secrets.KEY }}
```
