### ISSUE TITLE
SSH Key protected by a passphrase?

### ISSUE THREAD

**Issue by hadfiiw** [Burnett01/rsync-deployments#9]
Hello,

If my SSH key is protected by a passphrase, is there any way to have the action enter that passphrase when the key is used?

`
Enter passphrase for (stdin): Warning: Permanently added '[<myhost.com>]:yy,[xxx.xxx.xxx.xxx]:yy' (RSA) to the list of known hosts.
`

Thanks!
Ian

**Comment by hadfiiw** [comment]
Just as another data point, if I use a new SSH key without a passphrase, everything is working as expected.

**Comment by Burnett01** [comment]
Hello @hadfiiw thank's for reaching out.
This action does not support passphrase protected ssh keys.
You could try and set the environment variable `RSYNC_PASSWORD` in your workflow to test whether this works.
For example:

```
jobs:
  testing-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set key passphrase
       env:
          RSYNC_PASSWORD: ${{ secrets.DEPLOY_KEY_PASSPHRASE}}
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /var/www/html/
        remote_host: example.com
        remote_user: debian
        remote_key: ${{ secrets.DEPLOY_KEY }}
```

I doubt this will work but might be worth a try.

**Comment by hadfiiw** [comment]
Thanks @Burnett01 .  I'll give that a shot and report back.

**Comment by hadfiiw** [comment]
So I did have to chance it up a little (the indenting seemed to be off):

```
    - uses: actions/checkout@v2
    - name: Set key passphrase
      env:
        RSYNC_PASSWORD: ${{ secrets.DEPLOY_KEY_PASSPHRASE}}
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
```

Which produced the error of...

```every step must define a `uses` or `run` key```

**Comment by Burnett01** [comment]
Ok @hadfiiw, please try the following:

```
    steps:
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: /var/www/html/
          remote_host: example.com
          remote_user: debian
          remote_key: ${{ secrets.DEPLOY_KEY }}
        env:
          RSYNC_PASSWORD: ${{ secrets.DEPLOY_KEY_PASSPHRASE}
```
